ci(ipa): use release tags for IPA ruleset (#889)

diff --git a/.github/workflows/ipa-changelog.yml b/.github/workflows/ipa-changelog.yml
--- a/.github/workflows/ipa-changelog.yml
+++ b/.github/workflows/ipa-changelog.yml
@@ -32,20 +32,23 @@ jobs:
       env: 
         VERSION_BUMP: ${{ steps.version_check.outputs.version_changed }}
       run: | 
-        npm run gen-ipa-changelog
-
-        # Check for uncommitted changes specific to CHANGELOG.md  
-        uncommitted_changes=$(git status --porcelain | grep "CHANGELOG.md" || echo "")  
-
-        diff_changelog=$(git diff -- tools/spectral/ipa/CHANGELOG.md || echo "")  
+        diff_changelog=$(git diff origin/main -- CHANGELOG.md || echo "")  
+        
+        echo "Changelog diff: ${diff_changelog}"
   
-        if [[ "${VERSION_BUMP}" == "false" && -n "${uncommitted_changes}" ]]; then  
+        if [[ "${VERSION_BUMP}" == "false" && -n "${diff_changelog}" ]]; then  
           echo "Error: Changelog should only be updated alongside a version bump. Please restore the changelog."  
           exit 1  
         fi  
-  
-        if [[ "${VERSION_BUMP}" == "true" && -n "${diff_changelog}" ]]; then  
-          echo "Error: Changelog must be updated alongside a version bump. Please run 'npm run gen-ipa-changelog' from the ipa directory and commit the changes."  
+        
+        npm run gen-ipa-changelog
+
+        # Check CHANGELOG.md is the generated changelog result
+        uncommitted_changes=$(git status --porcelain | grep "CHANGELOG.md" || echo "")  
+        
+        if [[ "${VERSION_BUMP}" == "true" && -n "${uncommitted_changes}" ]]; then  
+          echo "Error: Changelog is not the same as the generated result. Please run 'npm run gen-ipa-changelog' from the ipa directory and commit the changes."  
           exit 1  
         fi 
+        
         exit 0
