Fix

diff --git a/.github/workflows/release-IPA-metrics.yml b/.github/workflows/release-IPA-metrics.yml
--- a/.github/workflows/release-IPA-metrics.yml
+++ b/.github/workflows/release-IPA-metrics.yml
@@ -53,9 +53,19 @@ jobs:
         with:
           name: oas-dev
 
+      - name: Debug Checkout
+        run: |
+          echo "Workspace Contents:"
+          ls -la
+          echo "Tools Spectral Contents:"
+          ls -la tools/spectral
+          echo "IPA Contents:"
+          ls -la tools/spectral/ipa || echo "ipa directory is missing!"
+
       - name: Run Metric Collection Job
         working-directory: tools/spectral/ipa/metrics/scripts
-        run: node runMetricCollection.js ${{ env.OAS_FILE }}
+        run: ls -la
+        # node runMetricCollection.js ${{ env.OAS_FILE }}
 
 #      - name: Dump Metric Collection Job Data to S3
 #        env:
