Fix

diff --git a/.github/workflows/release-IPA-metrics.yml b/.github/workflows/release-IPA-metrics.yml
--- a/.github/workflows/release-IPA-metrics.yml
+++ b/.github/workflows/release-IPA-metrics.yml
@@ -24,7 +24,7 @@ jobs:
         uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
         with:
           sparse-checkout:
-              tools/spectral
+              tools/spectral/ipa
               package.json
               package-lock.json
 
@@ -41,6 +41,15 @@ jobs:
             echo "::error::OAS file not found in ${{ env.OAS_BRANCH }} branch"
             exit 1
           fi
+
+      - name: Debug Checkout
+        run: |
+          echo "Workspace Contents:"
+          ls -la
+          echo "Tools Spectral Contents:"
+          ls -la tools/spectral
+          echo "IPA Contents:"
+          ls -la tools/spectral/ipa || echo "ipa directory is missing!"
 
       - name: Setup Node
         uses: actions/setup-node@v4
